### ISSUE TITLE
Obstacles not moving

### ISSUE THREAD

**Issue by Saadmaghani** [aninair1905/DynaBARN#1]
Hi!

Im trying to get DynaBARN to work but the obstacles are not moving. They are just stuck in one place. This is being output when I run `gazebo world_0.world`:
Topic [/data://world/default/model/easylibobs_131/plugin/easylibobs_131/joint_cmd] is not valid.
Topic [/data://world/default/model/easylibobs_131/plugin/easylibobs_131/joint_cmd] is not valid.

I'm wondering whether my gazebo version is different and so the plugin files are outdated for my current gazebo version. My version is:
11.11.0

*EDIT*
I ran the command (in verbose mode) `gazebo world_0.world --verbose` and got the following output:
```
[Err] [Plugin.hh:212] Failed to load plugin /home/saadghani/jackal_ws/src/nav-competition-icra2022/jackal_helper/plugins/easylibobs_131.so: libgazebo_physics.so.9: cannot open shared object file: No such file or directory
[Err] [Plugin.hh:212] Failed to load plugin /home/saadghani/jackal_ws/src/nav-competition-icra2022/jackal_helper/plugins/easylibobs_42.so: libgazebo_physics.so.9: cannot open shared object file: No such file or directory
[Err] [Plugin.hh:212] Failed to load plugin /home/saadghani/jackal_ws/src/nav-competition-icra2022/jackal_helper/plugins/easylibobs_30.so: libgazebo_physics.so.9: cannot open shared object file: No such file or directory
[Err] [Plugin.hh:212] Failed to load plugin /home/saadghani/jackal_ws/src/nav-competition-icra2022/jackal_helper/plugins/easylibobs_37.so: libgazebo_physics.so.9: cannot open shared object file: No such file or directory
[Err] [Plugin.hh:212] Failed to load plugin /home/saadghani/jackal_ws/src/nav-competition-icra2022/jackal_helper/plugins/easylibobs_36.so: libgazebo_physics.so.9: cannot open shared object file: No such file or directory
[Err] [Plugin.hh:212] Failed to load plugin /home/saadghani/jackal_ws/src/nav-competition-icra2022/jackal_helper/plugins/easylibobs_134.so: libgazebo_physics.so.9: cannot open shared object file: No such file or directory
[Err] [Plugin.hh:212] Failed to load plugin /home/saadghani/jackal_ws/src/nav-competition-icra2022/jackal_helper/plugins/easylibobs_41.so: libgazebo_physics.so.9: cannot open shared object file: No such file or directory
```
Any idea on how to solve this?

I guess gazebo version is not the issue

**Comment by aninair1905** [comment]
Hello, 
I just checked and the Gazebo that I used is Gazebo 9.0, and I reran some of the worlds and they ran fine on my machine. And from what I read it looks like libgazebo_physics.so.9 is the physics plugin associated with gazebo 9. In fact, if you have gazebo 11, then you must have a file of the sort libgazebo_physics.so.11
If so then it is likely a gazebo version mismatch. 
**Another thing you can check** is that if Gazebo plugin path points to the folder with the plugins. I remember one reason why they weren't moving and I got the "Topic [/data://world/default/model/easylibobs_131/plugin/easylibobs_131/joint_cmd] is not valid." was because the plugin path was not set to the plugin directory.

**Comment by Saadmaghani** [comment]
Turns out it was a version issue. This is not compatible with Gazebo11 and Gazebo9 is not compatible with Ros Noetic and Ros Melodic is not easily installed on Ubuntu 20.04.

So I had to install Ubuntu 18.04 -> Ros melodic (and with it Gazebo9) and then everything worked!

Thank you very much Ani for the tip. Without it I was going in circles

**Comment by ltf1001** [comment]
> Hello, I just checked and the Gazebo that I used is Gazebo 9.0, and I reran some of the worlds and they ran fine on my machine. And from what I read it looks like libgazebo_physics.so.9 is the physics plugin associated with gazebo 9. In fact, if you have gazebo 11, then you must have a file of the sort libgazebo_physics.so.11 If so then it is likely a gazebo version mismatch. **Another thing you can check** is that if Gazebo plugin path points to the folder with the plugins. I remember one reason why they weren't moving and I got the "Topic [/data://world/default/model/easylibobs_131/plugin/easylibobs_131/joint_cmd] is not valid." was because the plugin path was not set to the plugin directory.

Hello author, I want to use this file as a performance testing platform. But the system I am currently using is Ubuntu 20.04. Is there any way for me to use this code without changing the platform?

**Comment by ltf1001** [comment]
> Hello, I just checked and the Gazebo that I used is Gazebo 9.0, and I reran some of the worlds and they ran fine on my machine. And from what I read it looks like libgazebo_physics.so.9 is the physics plugin associated with gazebo 9. In fact, if you have gazebo 11, then you must have a file of the sort libgazebo_physics.so.11 If so then it is likely a gazebo version mismatch. **Another thing you can check** is that if Gazebo plugin path points to the folder with the plugins. I remember one reason why they weren't moving and I got the "Topic [/data://world/default/model/easylibobs_131/plugin/easylibobs_131/joint_cmd] is not valid." was because the plugin path was not set to the plugin directory.

Hello, I want to use this file as a performance test platform. But the system I am currently using is Ubuntu 20.04, and there are obstacles that prevent movement. Is there any way for me to use this code without changing the platform?
